/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Computador;

/**
 *
 * @author lveloza1
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbMarca = new javax.swing.JComboBox();
        txtColor = new javax.swing.JTextField();
        txtCapDisco = new javax.swing.JTextField();
        txtCapRam = new javax.swing.JTextField();
        txtNucleos = new javax.swing.JTextField();
        cmbPantalla = new javax.swing.JComboBox();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Características Computador");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setText("Marca");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setText("Color");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel4.setText("Capacidad de disco (GB)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel5.setText("Capacidad de Ram (GB)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 250, 130));

        jLabel6.setText("Numero de Nucleos");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel7.setText("Tipo de pantalla");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        cmbMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dell", "Toshiba", "Apple", "Lenovo" }));
        jPanel1.add(cmbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 80, 30));
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 80, 70, 30));
        jPanel1.add(txtCapDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, 30));
        jPanel1.add(txtCapRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 60, 30));
        jPanel1.add(txtNucleos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 60, 30));

        cmbPantalla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Retina", "Normal" }));
        jPanel1.add(cmbPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 70, 30));

        cmdMostrar.setText("Mostrar Resultados");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 183, 140, 50));

        cmdBorrar.setText("Borrar");
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 283, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        int op1, op2, cdisc, cram, valor=0;
        Computador c1=null;
        op1 = cmbMarca.getSelectedIndex();
        op2 = cmbPantalla.getSelectedIndex();
        cdisc = Integer.parseInt(txtCapDisco.getText());
        cram = Integer.parseInt(txtCapRam.getText());

        switch (op1) {
            case 0:
                if ((cdisc >= 100) && (cram >= 2)) {
                    valor = 2000000;
                } else {
                    valor = 3000000;
                }
                break;
            case 1:
                if ((cdisc < 100) && (cram < 3)) {
                    valor = 1500000;
                } else {
                    valor = 3000000;
                }
                break;
            case 2:
                if ((cdisc >= 150) && (cram >= 2)) {
                    valor = 3300000;
                } else {
                    valor = 3000000;
                }
                break;
            case 3:
                if ((cdisc < 150) && (cram < 4)) {
                    valor = 1100000;
                } else {
                    valor = 3000000;
                }
                break;
      }  
      txtResultado.setText("" + valor +"\n"
      + "Color :" +txtColor.getText()+ "\n"
      + "Capacidad de disco:" +txtCapDisco.getText()+ "\n"
      + "Capacidad de Ram:" +txtCapRam.getText()+ "\n"
      + "Numero de Nucleos:" +txtNucleos.getText()); 
      

// TODO add your handling code here:
    }//GEN-LAST:event_cmdMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbMarca;
    private javax.swing.JComboBox cmbPantalla;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCapDisco;
    private javax.swing.JTextField txtCapRam;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtNucleos;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
